// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UsersGet.proto

#ifndef PROTOBUF_UsersGet_2eproto__INCLUDED
#define PROTOBUF_UsersGet_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "User.pb.h"
// @@protoc_insertion_point(includes)
class User;
class UserDefaultTypeInternal;
extern UserDefaultTypeInternal _User_default_instance_;
class UserAuthenticateRequest;
class UserAuthenticateRequestDefaultTypeInternal;
extern UserAuthenticateRequestDefaultTypeInternal _UserAuthenticateRequest_default_instance_;
class UserAuthenticateResponse;
class UserAuthenticateResponseDefaultTypeInternal;
extern UserAuthenticateResponseDefaultTypeInternal _UserAuthenticateResponse_default_instance_;
class UserGetRequest;
class UserGetRequestDefaultTypeInternal;
extern UserGetRequestDefaultTypeInternal _UserGetRequest_default_instance_;
class UserGetResponse;
class UserGetResponseDefaultTypeInternal;
extern UserGetResponseDefaultTypeInternal _UserGetResponse_default_instance_;

namespace protobuf_UsersGet_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_UsersGet_2eproto

// ===================================================================

class UserGetRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UserGetRequest) */ {
 public:
  UserGetRequest();
  virtual ~UserGetRequest();

  UserGetRequest(const UserGetRequest& from);

  inline UserGetRequest& operator=(const UserGetRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserGetRequest& default_instance();

  static inline const UserGetRequest* internal_default_instance() {
    return reinterpret_cast<const UserGetRequest*>(
               &_UserGetRequest_default_instance_);
  }

  void Swap(UserGetRequest* other);

  // implements Message ----------------------------------------------

  inline UserGetRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  UserGetRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UserGetRequest& from);
  void MergeFrom(const UserGetRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UserGetRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // @@protoc_insertion_point(class_scope:UserGetRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  mutable int _cached_size_;
  friend struct  protobuf_UsersGet_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UserGetResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UserGetResponse) */ {
 public:
  UserGetResponse();
  virtual ~UserGetResponse();

  UserGetResponse(const UserGetResponse& from);

  inline UserGetResponse& operator=(const UserGetResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserGetResponse& default_instance();

  static inline const UserGetResponse* internal_default_instance() {
    return reinterpret_cast<const UserGetResponse*>(
               &_UserGetResponse_default_instance_);
  }

  void Swap(UserGetResponse* other);

  // implements Message ----------------------------------------------

  inline UserGetResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  UserGetResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UserGetResponse& from);
  void MergeFrom(const UserGetResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UserGetResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string error = 3;
  void clear_error();
  static const int kErrorFieldNumber = 3;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // .User user = 1;
  bool has_user() const;
  void clear_user();
  static const int kUserFieldNumber = 1;
  const ::User& user() const;
  ::User* mutable_user();
  ::User* release_user();
  void set_allocated_user(::User* user);

  // bool valid = 2;
  void clear_valid();
  static const int kValidFieldNumber = 2;
  bool valid() const;
  void set_valid(bool value);

  // @@protoc_insertion_point(class_scope:UserGetResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr error_;
  ::User* user_;
  bool valid_;
  mutable int _cached_size_;
  friend struct  protobuf_UsersGet_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UserAuthenticateRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UserAuthenticateRequest) */ {
 public:
  UserAuthenticateRequest();
  virtual ~UserAuthenticateRequest();

  UserAuthenticateRequest(const UserAuthenticateRequest& from);

  inline UserAuthenticateRequest& operator=(const UserAuthenticateRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserAuthenticateRequest& default_instance();

  static inline const UserAuthenticateRequest* internal_default_instance() {
    return reinterpret_cast<const UserAuthenticateRequest*>(
               &_UserAuthenticateRequest_default_instance_);
  }

  void Swap(UserAuthenticateRequest* other);

  // implements Message ----------------------------------------------

  inline UserAuthenticateRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  UserAuthenticateRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UserAuthenticateRequest& from);
  void MergeFrom(const UserAuthenticateRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UserAuthenticateRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string username = 1;
  void clear_username();
  static const int kUsernameFieldNumber = 1;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // string password = 2;
  void clear_password();
  static const int kPasswordFieldNumber = 2;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // string ip = 3;
  void clear_ip();
  static const int kIpFieldNumber = 3;
  const ::std::string& ip() const;
  void set_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_ip(::std::string&& value);
  #endif
  void set_ip(const char* value);
  void set_ip(const char* value, size_t size);
  ::std::string* mutable_ip();
  ::std::string* release_ip();
  void set_allocated_ip(::std::string* ip);

  // string token = 4;
  void clear_token();
  static const int kTokenFieldNumber = 4;
  const ::std::string& token() const;
  void set_token(const ::std::string& value);
  #if LANG_CXX11
  void set_token(::std::string&& value);
  #endif
  void set_token(const char* value);
  void set_token(const char* value, size_t size);
  ::std::string* mutable_token();
  ::std::string* release_token();
  void set_allocated_token(::std::string* token);

  // @@protoc_insertion_point(class_scope:UserAuthenticateRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  ::google::protobuf::internal::ArenaStringPtr ip_;
  ::google::protobuf::internal::ArenaStringPtr token_;
  mutable int _cached_size_;
  friend struct  protobuf_UsersGet_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UserAuthenticateResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UserAuthenticateResponse) */ {
 public:
  UserAuthenticateResponse();
  virtual ~UserAuthenticateResponse();

  UserAuthenticateResponse(const UserAuthenticateResponse& from);

  inline UserAuthenticateResponse& operator=(const UserAuthenticateResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserAuthenticateResponse& default_instance();

  static inline const UserAuthenticateResponse* internal_default_instance() {
    return reinterpret_cast<const UserAuthenticateResponse*>(
               &_UserAuthenticateResponse_default_instance_);
  }

  void Swap(UserAuthenticateResponse* other);

  // implements Message ----------------------------------------------

  inline UserAuthenticateResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  UserAuthenticateResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UserAuthenticateResponse& from);
  void MergeFrom(const UserAuthenticateResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UserAuthenticateResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string auths = 3;
  int auths_size() const;
  void clear_auths();
  static const int kAuthsFieldNumber = 3;
  const ::std::string& auths(int index) const;
  ::std::string* mutable_auths(int index);
  void set_auths(int index, const ::std::string& value);
  void set_auths(int index, const char* value);
  void set_auths(int index, const char* value, size_t size);
  ::std::string* add_auths();
  void add_auths(const ::std::string& value);
  void add_auths(const char* value);
  void add_auths(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& auths() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_auths();

  // string error = 4;
  void clear_error();
  static const int kErrorFieldNumber = 4;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // .User userAccount = 1;
  bool has_useraccount() const;
  void clear_useraccount();
  static const int kUserAccountFieldNumber = 1;
  const ::User& useraccount() const;
  ::User* mutable_useraccount();
  ::User* release_useraccount();
  void set_allocated_useraccount(::User* useraccount);

  // bool authenticated = 2;
  void clear_authenticated();
  static const int kAuthenticatedFieldNumber = 2;
  bool authenticated() const;
  void set_authenticated(bool value);

  // @@protoc_insertion_point(class_scope:UserAuthenticateResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> auths_;
  ::google::protobuf::internal::ArenaStringPtr error_;
  ::User* useraccount_;
  bool authenticated_;
  mutable int _cached_size_;
  friend struct  protobuf_UsersGet_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// UserGetRequest

// string id = 1;
inline void UserGetRequest::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserGetRequest::id() const {
  // @@protoc_insertion_point(field_get:UserGetRequest.id)
  return id_.GetNoArena();
}
inline void UserGetRequest::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UserGetRequest.id)
}
#if LANG_CXX11
inline void UserGetRequest::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UserGetRequest.id)
}
#endif
inline void UserGetRequest::set_id(const char* value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UserGetRequest.id)
}
inline void UserGetRequest::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UserGetRequest.id)
}
inline ::std::string* UserGetRequest::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:UserGetRequest.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserGetRequest::release_id() {
  // @@protoc_insertion_point(field_release:UserGetRequest.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserGetRequest::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:UserGetRequest.id)
}

// -------------------------------------------------------------------

// UserGetResponse

// .User user = 1;
inline bool UserGetResponse::has_user() const {
  return this != internal_default_instance() && user_ != NULL;
}
inline void UserGetResponse::clear_user() {
  if (GetArenaNoVirtual() == NULL && user_ != NULL) delete user_;
  user_ = NULL;
}
inline const ::User& UserGetResponse::user() const {
  // @@protoc_insertion_point(field_get:UserGetResponse.user)
  return user_ != NULL ? *user_
                         : *::User::internal_default_instance();
}
inline ::User* UserGetResponse::mutable_user() {
  
  if (user_ == NULL) {
    user_ = new ::User;
  }
  // @@protoc_insertion_point(field_mutable:UserGetResponse.user)
  return user_;
}
inline ::User* UserGetResponse::release_user() {
  // @@protoc_insertion_point(field_release:UserGetResponse.user)
  
  ::User* temp = user_;
  user_ = NULL;
  return temp;
}
inline void UserGetResponse::set_allocated_user(::User* user) {
  delete user_;
  user_ = user;
  if (user) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:UserGetResponse.user)
}

// bool valid = 2;
inline void UserGetResponse::clear_valid() {
  valid_ = false;
}
inline bool UserGetResponse::valid() const {
  // @@protoc_insertion_point(field_get:UserGetResponse.valid)
  return valid_;
}
inline void UserGetResponse::set_valid(bool value) {
  
  valid_ = value;
  // @@protoc_insertion_point(field_set:UserGetResponse.valid)
}

// string error = 3;
inline void UserGetResponse::clear_error() {
  error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserGetResponse::error() const {
  // @@protoc_insertion_point(field_get:UserGetResponse.error)
  return error_.GetNoArena();
}
inline void UserGetResponse::set_error(const ::std::string& value) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UserGetResponse.error)
}
#if LANG_CXX11
inline void UserGetResponse::set_error(::std::string&& value) {
  
  error_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UserGetResponse.error)
}
#endif
inline void UserGetResponse::set_error(const char* value) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UserGetResponse.error)
}
inline void UserGetResponse::set_error(const char* value, size_t size) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UserGetResponse.error)
}
inline ::std::string* UserGetResponse::mutable_error() {
  
  // @@protoc_insertion_point(field_mutable:UserGetResponse.error)
  return error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserGetResponse::release_error() {
  // @@protoc_insertion_point(field_release:UserGetResponse.error)
  
  return error_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserGetResponse::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    
  } else {
    
  }
  error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:UserGetResponse.error)
}

// -------------------------------------------------------------------

// UserAuthenticateRequest

// string username = 1;
inline void UserAuthenticateRequest::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAuthenticateRequest::username() const {
  // @@protoc_insertion_point(field_get:UserAuthenticateRequest.username)
  return username_.GetNoArena();
}
inline void UserAuthenticateRequest::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UserAuthenticateRequest.username)
}
#if LANG_CXX11
inline void UserAuthenticateRequest::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UserAuthenticateRequest.username)
}
#endif
inline void UserAuthenticateRequest::set_username(const char* value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UserAuthenticateRequest.username)
}
inline void UserAuthenticateRequest::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UserAuthenticateRequest.username)
}
inline ::std::string* UserAuthenticateRequest::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:UserAuthenticateRequest.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAuthenticateRequest::release_username() {
  // @@protoc_insertion_point(field_release:UserAuthenticateRequest.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAuthenticateRequest::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:UserAuthenticateRequest.username)
}

// string password = 2;
inline void UserAuthenticateRequest::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAuthenticateRequest::password() const {
  // @@protoc_insertion_point(field_get:UserAuthenticateRequest.password)
  return password_.GetNoArena();
}
inline void UserAuthenticateRequest::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UserAuthenticateRequest.password)
}
#if LANG_CXX11
inline void UserAuthenticateRequest::set_password(::std::string&& value) {
  
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UserAuthenticateRequest.password)
}
#endif
inline void UserAuthenticateRequest::set_password(const char* value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UserAuthenticateRequest.password)
}
inline void UserAuthenticateRequest::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UserAuthenticateRequest.password)
}
inline ::std::string* UserAuthenticateRequest::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:UserAuthenticateRequest.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAuthenticateRequest::release_password() {
  // @@protoc_insertion_point(field_release:UserAuthenticateRequest.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAuthenticateRequest::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:UserAuthenticateRequest.password)
}

// string ip = 3;
inline void UserAuthenticateRequest::clear_ip() {
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAuthenticateRequest::ip() const {
  // @@protoc_insertion_point(field_get:UserAuthenticateRequest.ip)
  return ip_.GetNoArena();
}
inline void UserAuthenticateRequest::set_ip(const ::std::string& value) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UserAuthenticateRequest.ip)
}
#if LANG_CXX11
inline void UserAuthenticateRequest::set_ip(::std::string&& value) {
  
  ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UserAuthenticateRequest.ip)
}
#endif
inline void UserAuthenticateRequest::set_ip(const char* value) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UserAuthenticateRequest.ip)
}
inline void UserAuthenticateRequest::set_ip(const char* value, size_t size) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UserAuthenticateRequest.ip)
}
inline ::std::string* UserAuthenticateRequest::mutable_ip() {
  
  // @@protoc_insertion_point(field_mutable:UserAuthenticateRequest.ip)
  return ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAuthenticateRequest::release_ip() {
  // @@protoc_insertion_point(field_release:UserAuthenticateRequest.ip)
  
  return ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAuthenticateRequest::set_allocated_ip(::std::string* ip) {
  if (ip != NULL) {
    
  } else {
    
  }
  ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip);
  // @@protoc_insertion_point(field_set_allocated:UserAuthenticateRequest.ip)
}

// string token = 4;
inline void UserAuthenticateRequest::clear_token() {
  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAuthenticateRequest::token() const {
  // @@protoc_insertion_point(field_get:UserAuthenticateRequest.token)
  return token_.GetNoArena();
}
inline void UserAuthenticateRequest::set_token(const ::std::string& value) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UserAuthenticateRequest.token)
}
#if LANG_CXX11
inline void UserAuthenticateRequest::set_token(::std::string&& value) {
  
  token_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UserAuthenticateRequest.token)
}
#endif
inline void UserAuthenticateRequest::set_token(const char* value) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UserAuthenticateRequest.token)
}
inline void UserAuthenticateRequest::set_token(const char* value, size_t size) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UserAuthenticateRequest.token)
}
inline ::std::string* UserAuthenticateRequest::mutable_token() {
  
  // @@protoc_insertion_point(field_mutable:UserAuthenticateRequest.token)
  return token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAuthenticateRequest::release_token() {
  // @@protoc_insertion_point(field_release:UserAuthenticateRequest.token)
  
  return token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAuthenticateRequest::set_allocated_token(::std::string* token) {
  if (token != NULL) {
    
  } else {
    
  }
  token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), token);
  // @@protoc_insertion_point(field_set_allocated:UserAuthenticateRequest.token)
}

// -------------------------------------------------------------------

// UserAuthenticateResponse

// .User userAccount = 1;
inline bool UserAuthenticateResponse::has_useraccount() const {
  return this != internal_default_instance() && useraccount_ != NULL;
}
inline void UserAuthenticateResponse::clear_useraccount() {
  if (GetArenaNoVirtual() == NULL && useraccount_ != NULL) delete useraccount_;
  useraccount_ = NULL;
}
inline const ::User& UserAuthenticateResponse::useraccount() const {
  // @@protoc_insertion_point(field_get:UserAuthenticateResponse.userAccount)
  return useraccount_ != NULL ? *useraccount_
                         : *::User::internal_default_instance();
}
inline ::User* UserAuthenticateResponse::mutable_useraccount() {
  
  if (useraccount_ == NULL) {
    useraccount_ = new ::User;
  }
  // @@protoc_insertion_point(field_mutable:UserAuthenticateResponse.userAccount)
  return useraccount_;
}
inline ::User* UserAuthenticateResponse::release_useraccount() {
  // @@protoc_insertion_point(field_release:UserAuthenticateResponse.userAccount)
  
  ::User* temp = useraccount_;
  useraccount_ = NULL;
  return temp;
}
inline void UserAuthenticateResponse::set_allocated_useraccount(::User* useraccount) {
  delete useraccount_;
  useraccount_ = useraccount;
  if (useraccount) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:UserAuthenticateResponse.userAccount)
}

// bool authenticated = 2;
inline void UserAuthenticateResponse::clear_authenticated() {
  authenticated_ = false;
}
inline bool UserAuthenticateResponse::authenticated() const {
  // @@protoc_insertion_point(field_get:UserAuthenticateResponse.authenticated)
  return authenticated_;
}
inline void UserAuthenticateResponse::set_authenticated(bool value) {
  
  authenticated_ = value;
  // @@protoc_insertion_point(field_set:UserAuthenticateResponse.authenticated)
}

// repeated string auths = 3;
inline int UserAuthenticateResponse::auths_size() const {
  return auths_.size();
}
inline void UserAuthenticateResponse::clear_auths() {
  auths_.Clear();
}
inline const ::std::string& UserAuthenticateResponse::auths(int index) const {
  // @@protoc_insertion_point(field_get:UserAuthenticateResponse.auths)
  return auths_.Get(index);
}
inline ::std::string* UserAuthenticateResponse::mutable_auths(int index) {
  // @@protoc_insertion_point(field_mutable:UserAuthenticateResponse.auths)
  return auths_.Mutable(index);
}
inline void UserAuthenticateResponse::set_auths(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:UserAuthenticateResponse.auths)
  auths_.Mutable(index)->assign(value);
}
inline void UserAuthenticateResponse::set_auths(int index, const char* value) {
  auths_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:UserAuthenticateResponse.auths)
}
inline void UserAuthenticateResponse::set_auths(int index, const char* value, size_t size) {
  auths_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:UserAuthenticateResponse.auths)
}
inline ::std::string* UserAuthenticateResponse::add_auths() {
  // @@protoc_insertion_point(field_add_mutable:UserAuthenticateResponse.auths)
  return auths_.Add();
}
inline void UserAuthenticateResponse::add_auths(const ::std::string& value) {
  auths_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:UserAuthenticateResponse.auths)
}
inline void UserAuthenticateResponse::add_auths(const char* value) {
  auths_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:UserAuthenticateResponse.auths)
}
inline void UserAuthenticateResponse::add_auths(const char* value, size_t size) {
  auths_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:UserAuthenticateResponse.auths)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
UserAuthenticateResponse::auths() const {
  // @@protoc_insertion_point(field_list:UserAuthenticateResponse.auths)
  return auths_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
UserAuthenticateResponse::mutable_auths() {
  // @@protoc_insertion_point(field_mutable_list:UserAuthenticateResponse.auths)
  return &auths_;
}

// string error = 4;
inline void UserAuthenticateResponse::clear_error() {
  error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserAuthenticateResponse::error() const {
  // @@protoc_insertion_point(field_get:UserAuthenticateResponse.error)
  return error_.GetNoArena();
}
inline void UserAuthenticateResponse::set_error(const ::std::string& value) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:UserAuthenticateResponse.error)
}
#if LANG_CXX11
inline void UserAuthenticateResponse::set_error(::std::string&& value) {
  
  error_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:UserAuthenticateResponse.error)
}
#endif
inline void UserAuthenticateResponse::set_error(const char* value) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:UserAuthenticateResponse.error)
}
inline void UserAuthenticateResponse::set_error(const char* value, size_t size) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:UserAuthenticateResponse.error)
}
inline ::std::string* UserAuthenticateResponse::mutable_error() {
  
  // @@protoc_insertion_point(field_mutable:UserAuthenticateResponse.error)
  return error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserAuthenticateResponse::release_error() {
  // @@protoc_insertion_point(field_release:UserAuthenticateResponse.error)
  
  return error_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserAuthenticateResponse::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    
  } else {
    
  }
  error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:UserAuthenticateResponse.error)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UsersGet_2eproto__INCLUDED
