// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: UsersGet.proto
#ifndef GRPC_UsersGet_2eproto__INCLUDED
#define GRPC_UsersGet_2eproto__INCLUDED

#include "UsersGet.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class Users final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetUserById(::grpc::ClientContext* context, const ::UserGetRequest& request, ::UserGetResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UserGetResponse>> AsyncGetUserById(::grpc::ClientContext* context, const ::UserGetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UserGetResponse>>(AsyncGetUserByIdRaw(context, request, cq));
    }
    virtual ::grpc::Status AuthenticateUser(::grpc::ClientContext* context, const ::UserAuthenticateRequest& request, ::UserAuthenticateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UserAuthenticateResponse>> AsyncAuthenticateUser(::grpc::ClientContext* context, const ::UserAuthenticateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UserAuthenticateResponse>>(AsyncAuthenticateUserRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UserGetResponse>* AsyncGetUserByIdRaw(::grpc::ClientContext* context, const ::UserGetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UserAuthenticateResponse>* AsyncAuthenticateUserRaw(::grpc::ClientContext* context, const ::UserAuthenticateRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetUserById(::grpc::ClientContext* context, const ::UserGetRequest& request, ::UserGetResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UserGetResponse>> AsyncGetUserById(::grpc::ClientContext* context, const ::UserGetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UserGetResponse>>(AsyncGetUserByIdRaw(context, request, cq));
    }
    ::grpc::Status AuthenticateUser(::grpc::ClientContext* context, const ::UserAuthenticateRequest& request, ::UserAuthenticateResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UserAuthenticateResponse>> AsyncAuthenticateUser(::grpc::ClientContext* context, const ::UserAuthenticateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UserAuthenticateResponse>>(AsyncAuthenticateUserRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::UserGetResponse>* AsyncGetUserByIdRaw(::grpc::ClientContext* context, const ::UserGetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::UserAuthenticateResponse>* AsyncAuthenticateUserRaw(::grpc::ClientContext* context, const ::UserAuthenticateRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_GetUserById_;
    const ::grpc::RpcMethod rpcmethod_AuthenticateUser_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetUserById(::grpc::ServerContext* context, const ::UserGetRequest* request, ::UserGetResponse* response);
    virtual ::grpc::Status AuthenticateUser(::grpc::ServerContext* context, const ::UserAuthenticateRequest* request, ::UserAuthenticateResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetUserById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetUserById() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetUserById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserById(::grpc::ServerContext* context, const ::UserGetRequest* request, ::UserGetResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUserById(::grpc::ServerContext* context, ::UserGetRequest* request, ::grpc::ServerAsyncResponseWriter< ::UserGetResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AuthenticateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_AuthenticateUser() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_AuthenticateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthenticateUser(::grpc::ServerContext* context, const ::UserAuthenticateRequest* request, ::UserAuthenticateResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAuthenticateUser(::grpc::ServerContext* context, ::UserAuthenticateRequest* request, ::grpc::ServerAsyncResponseWriter< ::UserAuthenticateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetUserById<WithAsyncMethod_AuthenticateUser<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_GetUserById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetUserById() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetUserById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserById(::grpc::ServerContext* context, const ::UserGetRequest* request, ::UserGetResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AuthenticateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_AuthenticateUser() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_AuthenticateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthenticateUser(::grpc::ServerContext* context, const ::UserAuthenticateRequest* request, ::UserAuthenticateResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetUserById : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetUserById() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::UserGetRequest, ::UserGetResponse>(std::bind(&WithStreamedUnaryMethod_GetUserById<BaseClass>::StreamedGetUserById, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetUserById() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetUserById(::grpc::ServerContext* context, const ::UserGetRequest* request, ::UserGetResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetUserById(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::UserGetRequest,::UserGetResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AuthenticateUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_AuthenticateUser() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::StreamedUnaryHandler< ::UserAuthenticateRequest, ::UserAuthenticateResponse>(std::bind(&WithStreamedUnaryMethod_AuthenticateUser<BaseClass>::StreamedAuthenticateUser, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_AuthenticateUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AuthenticateUser(::grpc::ServerContext* context, const ::UserAuthenticateRequest* request, ::UserAuthenticateResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAuthenticateUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::UserAuthenticateRequest,::UserAuthenticateResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetUserById<WithStreamedUnaryMethod_AuthenticateUser<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetUserById<WithStreamedUnaryMethod_AuthenticateUser<Service > > StreamedService;
};


#endif  // GRPC_UsersGet_2eproto__INCLUDED
